VAR_GLOBAL
    HMI_r取料气缸打开延时 			AT %MD15500:REAL; 	
    HMI_r取料气缸关闭延时 			AT %MD15501:REAL; 	
			
    HMI_r纠偏气缸打开延时			AT %MD15502:REAL; 	
    HMI_r纠偏气缸关闭延时 			AT %MD15503:REAL; 	
	
    HMI_r挡料定位气缸打开延时 	 	AT %MD15504:REAL; 	
    HMI_r挡料定位气缸关闭延时 	 	AT %MD15505:REAL; 	
	 
    HMI_r翻板气缸打开延时 		 	AT %MD15506:REAL; 	
    HMI_r翻板气缸关闭延时 		 	AT %MD15507:REAL; 	
			
    HMI_r侧压紧气缸打开延时 	 	AT %MD15508:REAL; 	
    HMI_r侧压紧气缸关闭延时 	 	AT %MD15509:REAL; 	
	
    HMI_r左A包底气缸打开延时 	 	AT %MD15510:REAL; 	
    HMI_r左A包底气缸关闭延时 	 	AT %MD15511:REAL; 	
	
    HMI_r右B包底气缸打开延时 	 	AT %MD15512:REAL; 	
    HMI_r右B包底气缸关闭延时 	 	AT %MD15513:REAL; 	
		
    HMI_r上包底气缸打开延时   		AT %MD15514:REAL; 
    HMI_r上包底气缸关闭延时   		AT %MD15515:REAL; 


    HMI_r下包底气缸打开延时   		AT %MD15516:REAL; 
    HMI_r下包底气缸关闭延时   		AT %MD15517:REAL; 

    HMI_r出料推盒气缸打开延时 	 	AT %MD15518:REAL; 	
    HMI_r出料推盒气缸关闭延时 	 	AT %MD15519:REAL; 	
	
    HMI_r包盒口升降气缸打开延时 	AT %MD15520:REAL; 	
    HMI_r包盒口升降气缸关闭延时 	AT %MD15521:REAL; 	

    HMI_r包盒口下压气缸打开延时 	AT %MD15522:REAL; 	
    HMI_r包盒口下压气缸关闭延时 	AT %MD15523:REAL; 	
	
    HMI_r翻底板气缸打开延时 		AT %MD15524:REAL; 	
    HMI_r翻底板气缸关闭延时 		AT %MD15525:REAL; 
		
    HMI_r推底板气缸打开延时 	 	AT %MD15526:REAL; 	
    HMI_r推底板气缸关闭延时 	 	AT %MD15527:REAL; 	
	
    HMI_r模组吸底板气缸打开延时 	AT %MD15528:REAL; 	
    HMI_r模组吸底板气缸关闭延时 	AT %MD15529:REAL; 	


    HMI_r包边纠偏上下气缸打开延时 	AT %MD15530:REAL; 	
    HMI_r包边纠偏上下气缸关闭延时 	AT %MD15531:REAL; 
	
    HMI_r包边纠偏左右气缸打开延时 	AT %MD15532:REAL; 	
    HMI_r包边纠偏左右气缸关闭延时 	AT %MD15533:REAL; 
	
    HMI_r包边压料气缸打开延时 	 	AT %MD15534:REAL; 	
    HMI_r包边压料气缸关闭延时 	 	AT %MD15535:REAL; 
	
    HMI_r折边上托气缸打开延时 	 	AT %MD15536:REAL; 	
    HMI_r折边上托气缸关闭延时 	 	AT %MD15537:REAL; 	
	
    HMI_r包边铲边气缸打开延时 		AT %MD15538:REAL; 	
    HMI_r包边铲边气缸关闭延时 		AT %MD15539:REAL;


    HMI_r吸底板真空打开延时 	 	AT %MD15540:REAL; 
    HMI_r吸底板真空关闭延时 	 	AT %MD15541:REAL; 

    HMI_r取面板真空打开延时	     	AT %MD15542:REAL; 
    HMI_r取面板真空关闭延时	     	AT %MD15543:REAL; 

    HMI_rA模吸底板真空打开延时 	 	AT %MD15544:REAL; 
    HMI_rA模吸底板真空关闭延时 	 	AT %MD15545:REAL; 

    HMI_rA模吸面板真空打开延时	 	AT %MD15546:REAL; 
    HMI_rA模吸面板真空关闭延时	 	AT %MD15547:REAL; 

    HMI_rB模吸底板真空打开延时 	 	AT %MD15548:REAL; 
    HMI_rB模吸底板真空关闭延时 	 	AT %MD15549:REAL; 

    HMI_rB模吸面板真空打开延时	 	AT %MD15550:REAL; 
    HMI_rB模吸面板真空关闭延时		AT %MD15551:REAL; 


END_VAR
